### ISSUE TITLE
Error when running on RHEL 7

### ISSUE THREAD

**Issue by jwinderWCB** [singleplatform-eng/ansible-role-nessus-agent#11]
Ansible version: 2.7.0
Remote host OS: Red Hat Enterprise Linux 7.5

I get the following error.
   "msg": "Unsupported parameters for (yum) module: cache_valid_time Supported parameters include: allow_downgrade, autoremove, bugfix, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_only, enable_plugin, enablerepo, exclude, install_repoquery, installroot, list, name, releasever, security, skip_broken, state, update_cache, update_only, use_backend, validate_certs"

**Comment by wwaltersp** [comment]
I merged a fix to master that worked for centos 7 on my local test env. Can you try with master and if that fixes for you I will cut a new release.

**Comment by jwinderWCB** [comment]
Thank you!

That appears to have cleared up the issue, and I learned something new. I didn't realize you could do the default(omit) like that.

Thank you again!
